#Starts the instance when the TS3AudioBot is launched.
run = true
#This field will be automatically set when you call '!bot setup'.
#The bot will use the specified group to set/update the required permissions and add himself into it.
#You can set this field manually if you already have a preexisting group the bot should add himself to.
bot_group_id = 0

[connect]
#The address, ip or nickname (and port; default: 9987) of the TeamSpeak3 server
address = "localhost:9987"
#Client nickname when connecting.
name = "Dixibot"
#The server password. Leave empty for none.
server_password = { pw = "", hashed = false }
#Default channel when connecting. Use a channel path or "/<id>".
#Examples: "Home/Lobby", "/5", "Home/Afk \\/ Not Here".
channel = ""
#The default channel password. Leave empty for none.
channel_password = {  }
#Overrides the displayed version for the ts3 client. Leave empty for default.
client_version = {  }

[connect.identity]
#||| DO NOT MAKE THIS KEY PUBLIC ||| The client identity. You can import a teamspeak3 identity here too.
key = "MCoDAgbAAgEgAiEApY7dHTX4bMhuKCa5J3z1WyLyMLvnJTWBi8wT7AJtuhA="
#The client identity offset determining the security level.
offset = 64
#The client identity security level which should be calculated before connecting
#or -1 to generate on demand when connecting.
level = -1

[commands]

[commands.alias]

[reconnect]

[audio]
#When a new song starts the volume will be trimmed to between min and max.
#When the current volume already is between min and max nothing will happen.
#To completely or partially disable this feature, set min to 0 and/or max to 100.
volume = { default = 42.0 }

[playlists]

[history]

[events]
